# SPDX-License-Identifier: Apache-2.0
---
name: 'test: lint all code'
description: 'Composite action to lint all kind of files'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha
        path: .docs-gha

    - name: Read .nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
      
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: '.nvmrc'

    - name: npm install, lint
      shell: bash
      run: |
        npm ci
        npm run lint
        npm run typecheck        

    - name: markdown lint
      uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        globs: '**/*.md'
        separator: ','
