# SPDX-License-Identifier: Apache-2.0
---
name: 'test: spelling'
description: 'Composite action to test spelling'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha-2023
        path: .docs-gha-2023

    - name: Vale
      uses: errata-ai/vale-action@v2.0.1
      with:
        files: '["./docs/", "./blog/"]' 
        vale_flags: "--config ./.docs-gha-2023/spelling/config/.vale.ini --glob='!docs/**/*.js'"        
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

     