# SPDX-License-Identifier: Apache-2.0
---
name: 'Trivy'
description: 'Composite action to run trivy on the npm package.json'


inputs:
  TRIVY_SKIP_DB_UPDATE:
    description: "Whether trivy should use cache instead of pulling latest db"
    required: false
    default: true
  TRIVY_SKIP_JAVA_DB_UPDATE:
    description: "Whether trivy should use cache instead of pulling latest java db"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha
        path: .docs-gha

    # 0.29.0
    # Refer to https://github.com/aquasecurity/trivy-action#updating-caches-in-the-default-branch for the env vars 
    # also uses aquasecurity/setup-trivy@v0.2.2 / aquasecurity/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        cache: 'true'
      env:
        TRIVY_SKIP_DB_UPDATE: ${{ inputs.TRIVY_SKIP_DB_UPDATE && inputs.TRIVY_SKIP_DB_UPDATE != 'false' }}
        TRIVY_SKIP_JAVA_DB_UPDATE: ${{ inputs.TRIVY_SKIP_JAVA_DB_UPDATE && inputs.TRIVY_SKIP_JAVA_DB_UPDATE != 'false' }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
  