# SPDX-License-Identifier: Apache-2.0
---
name: 'deploy to github pages'
description: 'Composite action to deploy to github pages'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha-2023
        path: .docs-gha-2023

    - name: Read .nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
      
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/      

    - name: npm build
      shell: bash
      run: |
        npm ci --only=production
        npm run build

    - name: generate PR slug
      shell: sh
      id: generate_pr_slug
      run: echo "::set-output name=slug::PR-${{ github.event.number }}"   

    - name: Deploy Preview
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build # The folder the action should deploy.
        commit-message: Merge to main for ${{ steps.generate_pr_slug.outputs.slug }}
        single-commit: true

    # # Popular action to deploy to GitHub Pages:
    # # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ inputs.GITHUB_TOKEN }}
    #     # Build output to publish to the `gh-pages` branch:
    #     publish_dir: ./build
    #     # The following lines assign commit authorship to the official
    #     # GH-Actions bot for deploys to `gh-pages` branch:
    #     # https://github.com/actions/checkout/issues/13#issuecomment-724415212
    #     # The GH actions bot is used by default if you didn't specify the two fields.
    #     # You can swap them out with your own user credentials.
    #     user_name: github-actions[bot]
    #     user_email: 41898282+github-actions[bot]@users.noreply.github.com        
