# SPDX-License-Identifier: Apache-2.0
---
name: 'deploy to github pages'
description: 'Composite action to deploy to github pages'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha
        path: .docs-gha

    - name: Read .nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
      
    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/      

    - name: npm build
      shell: bash
      run: |
        npm ci --only=production
        npm run build

    - name: generate PR slug
      shell: sh
      id: generate_pr_slug
      run: echo "::set-output name=slug::PR-${{ github.event.number }}"   

    - name: Deploy Preview
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build # The folder the action should deploy.
        commit-message: Merge to main for ${{ steps.generate_pr_slug.outputs.slug }}
        single-commit: true
