# SPDX-License-Identifier: Apache-2.0
---
name: 'release to github'
description: 'Composite action to release to github'

inputs:
  GITHUB_TOKEN:
    description: 'Github secret Token'
    required: true
  SEMANTIC_RELEASE:
    description: 'whether to enable semantic-release versioning'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha-2023
        path: .docs-gha-2023

    - name: Read .nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        registry-url: https://registry.npmjs.org/
        node-version-file: '.nvmrc'

    - name: npm build
      shell: bash
      run: |
        npm ci
        npm run build

    - if: ${{ inputs.SEMANTIC_RELEASE }} == 'true'
      name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        HUSKY: 0 # disable hooks for release
      shell: bash
      run: npx semantic-release
