# SPDX-License-Identifier: Apache-2.0
---
name: 'lint: markdown'
description: 'Composite action to lint markdown'

inputs:
  CONFIG_FILE:
    description: 'markdownlint config file'
    required: false
    default: ".docs-gha/lint-markdown/.markdownlint.yaml"
  FILEPATHS:
    description: 'Filepaths to look at, specified as a comma separated string ie "docs/**/*.md,blog/**/*.md,etc"'
    required: false
    default: "docs/**/*.md"

runs:
  using: "composite"
  steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: Consensys/docs-gha
        path: .docs-gha

    # 2f7c5bfce28377bc069a65ba478de0a74aa0ca32 = v46.0.1 as at 18032025
    - uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32
      id: changed-files
      with:
        files:  ${{ inputs.FILEPATHS }}
        separator: ','

    - name: markdown lint
      if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
      uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        config: ${{ inputs.CONFIG_FILE }}
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ','
        # don't block the build - let it proceed
        #continue-on-error: true
