name: Algolia Search Scraper

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Trigger Algolia Scraper
    runs-on: ubuntu-latest
    environment: algolia
    strategy:
      matrix:
        version:
          [
            "teku",
            "goquorum",
            "zkevm",
            "tessera",
            "web3signer",
            "ethsigner",
            "qkm",
            "docs-template",
            "gnark",
          ]
    steps:
      - uses: actions/checkout@v3
      - id: config
        name: Read ${{ matrix.version }}.json
        shell: bash
        run: |
          content=$(cat ./.github/config/${{ matrix.version }}.json | jq -r tostring)
          echo "configJSON=$content" >> $GITHUB_OUTPUT
      - name: Algolia Docsearch Action
        id: algolia
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          CONFIG: ${{ steps.config.outputs.configJSON }}
        uses: adapttive/algolia-docsearch-action@1.1.1
